### ISSUE TITLE
Enhancement request: Option to mark lab results and scale predicted values

### ISSUE THREAD

**Issue by PersephoneKarnstein** [WHSAH/estrannaise.js#45]
Hi! Amazing work with the project! One enhancement i would like to see is the ability to mark lab results in the plot to compare them with the expected values; possibly with the option to apply a fractional scalar multiplier to the expectation curve. I know that I for one have a very poor absorption/availability of most medicines and my lab results are consistently significantly below the expected values for my dose, and this would be very helpful for properly predicting my cycle.

**Comment by a1ix2** [comment]
Funny you mention that, I was thinking about adding a field for a fractional multiplier for this exact reason barely a few days ago.

**Comment by a1ix2** [comment]
Added in https://github.com/WHSAH/estrannaise.js/commit/d94c45a2eeda0d951185029fde6cfb68bfba491e
